base_url                  = "https://tatsumin.dev"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Tatsumi тий"
theme                    = "zolasam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
compile_sass		 = true
build_search_index	 = true
[author]
    name		 = "Tatsumi"
[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Call me Sam, a theme for Hugo."
[markdown]
    highlight_code	 = true
# Metadata for Open Graph and Twitter
    description          = ""               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Call me Sam"
    # rss                = ""

    footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
# [[params.videoBackground.sources]]
#     source  = "/sample_video.mp4"
#     type    = "video/mp4"
#     poster  = "/background.png"
# [params.videoBackground]
#     overlay = "rgba(0, 0, 0, 0.4)" # optional

[extra]
sam_bottom_menu = true
sam_menu = [
    { text = "posts.", link = "/posts" },
    { text = "about.", link = "/about" },
    { text = "github.", link = "https://github.com/tatsumin21" },
    { text = "email.", link = "/contact"}
]
# [[params.mainMenu]]
#     link = "gallery"
#    text = "gallery"

# [[params.mainMenu]]
#    link = "portfolio"
#    text = "portfolio"
# [[params.mainMenu]]
#    link = "/posts"
#    text = "posts."

#[[params.mainMenu]]
#    link = "/about"
#    text = "about."
#[[params.mainMenu]]
#    link = "https://github.com/tatsumin21"
#    text = "github."
#[[params.mainMenu]]
#    link = "/contact"
#    text = "email."
#[imaging]
#    quality = 75
